package com.nzd.antigravitypanel.ui.component

import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.painter.Painter
import androidx.compose.ui.res.painterResource
import com.nzd.antigravitypanel.shared.R

/**
 * Build 计划图片的 Android 实现。
 *
 * **由 `tools/gen_build_data.py` 生成，别手改。**
 *
 * 名字在包里已有图（配装那批 `weapon_NNN` / `plugin_NNN`）时**直接复用**，
 * 只有对不上的才用脚本补出来的 `build_weapon_NNN` / `build_perk_NNN`。
 * 复用是为了不把同一张图打包两遍 —— 两批源图都是游戏内同一套美术。
 */
@Composable
actual fun buildWeaponPainter(name: String): Painter? {
    val id = when (name) {
        "Bully" -> R.drawable.weapon_001
        "Z型步枪" -> R.drawable.weapon_002
        "乘风快递" -> R.drawable.weapon_008
        "元宵来袭" -> R.drawable.weapon_009
        "光荣之路" -> R.drawable.weapon_012
        "共晶点" -> R.drawable.weapon_014
        "再生冷却" -> R.drawable.weapon_016
        "军用手斧" -> R.drawable.weapon_017
        "冥河之矛" -> R.drawable.weapon_020
        "冰川尼泊尔" -> R.drawable.weapon_021
        "冰点双峰" -> R.drawable.build_weapon_001
        "利齿" -> R.drawable.weapon_029
        "制式手枪" -> R.drawable.weapon_030
        "刺锋" -> R.drawable.weapon_031
        "刺隐" -> R.drawable.weapon_033
        "十字长枪" -> R.drawable.build_weapon_002
        "哈士奇好友" -> R.drawable.weapon_035
        "圣诞雪镐" -> R.drawable.build_weapon_003
        "夜影之逝" -> R.drawable.weapon_037
        "天鹅之舞" -> R.drawable.weapon_039
        "密林杀机" -> R.drawable.weapon_040
        "封刃" -> R.drawable.weapon_042
        "尸龙战斧" -> R.drawable.weapon_045
        "幽冥毒王" -> R.drawable.weapon_049
        "幽冥毒皇" -> R.drawable.weapon_051
        "往日速递" -> R.drawable.weapon_052
        "心有凌兮" -> R.drawable.weapon_053
        "怒目锤" -> R.drawable.weapon_054
        "战争矩阵" -> R.drawable.weapon_058
        "战锋" -> R.drawable.weapon_059
        "拂晓炎翎" -> R.drawable.build_weapon_004
        "振弦" -> R.drawable.weapon_060
        "撬棍" -> R.drawable.weapon_061
        "收割者" -> R.drawable.weapon_064
        "星海狂想" -> R.drawable.weapon_066
        "星铩" -> R.drawable.build_weapon_005
        "春雷震" -> R.drawable.weapon_067
        "暗夜之殇" -> R.drawable.weapon_071
        "木葫芦" -> R.drawable.weapon_076
        "未名之刃" -> R.drawable.build_weapon_006
        "杜瓦瓶" -> R.drawable.weapon_084
        "杰斯拳套" -> R.drawable.build_weapon_007
        "梦魇" -> R.drawable.weapon_085
        "棒球棍" -> R.drawable.weapon_086
        "樱之殇" -> R.drawable.weapon_087
        "樱之誓" -> R.drawable.build_weapon_008
        "武装斧头" -> R.drawable.weapon_088
        "死亡之拥" -> R.drawable.weapon_089
        "死亡猎手" -> R.drawable.weapon_092
        "死神猎手" -> R.drawable.weapon_096
        "死神镰刀" -> R.drawable.weapon_098
        "沙丘之怒" -> R.drawable.weapon_100
        "沙暴冷锋" -> R.drawable.weapon_101
        "沙蚀重刃" -> R.drawable.weapon_102
        "浪里白条" -> R.drawable.weapon_104
        "深渊之触" -> R.drawable.weapon_105
        "渡鸦剑" -> R.drawable.weapon_106
        "火山口" -> R.drawable.weapon_107
        "火炬" -> R.drawable.weapon_108
        "火神炎帝" -> R.drawable.weapon_111
        "炼狱双蝎" -> R.drawable.weapon_114
        "炼狱蝎王" -> R.drawable.weapon_118
        "爆星" -> R.drawable.weapon_120
        "狂人电锯" -> R.drawable.weapon_121
        "狂犬指套" -> R.drawable.build_weapon_009
        "猪猪捏捏乐" -> R.drawable.weapon_127
        "猪猪榴弹发射器" -> R.drawable.weapon_128
        "玄凌飞刃" -> R.drawable.weapon_131
        "生命公司" -> R.drawable.build_weapon_010
        "生命线" -> R.drawable.weapon_135
        "甩棍" -> R.drawable.weapon_136
        "疾影逐风" -> R.drawable.weapon_138
        "百炼钢管" -> R.drawable.weapon_139
        "短剑" -> R.drawable.weapon_140
        "秘魇锤" -> R.drawable.weapon_141
        "稳赢之手" -> R.drawable.weapon_142
        "精绝兽神" -> R.drawable.weapon_147
        "纯白至上" -> R.drawable.weapon_149
        "维和者" -> R.drawable.weapon_152
        "胜利誓约" -> R.drawable.weapon_154
        "能源之影" -> R.drawable.weapon_157
        "苔色暴风" -> R.drawable.weapon_163
        "葫芦" -> R.drawable.weapon_164
        "蛇神之剑" -> R.drawable.weapon_165
        "蛇神之矛" -> R.drawable.weapon_166
        "蜘蛛匕首" -> R.drawable.build_weapon_011
        "蝶翼双扇" -> R.drawable.weapon_167
        "血怨" -> R.drawable.weapon_169
        "裁决之眼" -> R.drawable.weapon_171
        "裂风" -> R.drawable.weapon_172
        "超级复合弓" -> R.drawable.weapon_177
        "逆光之刃" -> R.drawable.build_weapon_012
        "钢脊" -> R.drawable.weapon_182
        "钢铁之握" -> R.drawable.weapon_183
        "钢铁游隼" -> R.drawable.weapon_184
        "钢铁轰鸣" -> R.drawable.weapon_186
        "钢铁骑士" -> R.drawable.weapon_187
        "铁砧" -> R.drawable.weapon_191
        "铁骨" -> R.drawable.weapon_192
        "锻星力量" -> R.drawable.weapon_193
        "防暴棍" -> R.drawable.weapon_194
        "雷霆999" -> R.drawable.weapon_197
        "雷霆之影" -> R.drawable.weapon_200
        "震沙锏" -> R.drawable.weapon_201
        "霜蚀之牙" -> R.drawable.weapon_202
        "韶光樱影" -> R.drawable.weapon_205
        "飓风之锤" -> R.drawable.weapon_207
        "飓风之龙" -> R.drawable.weapon_209
        "马来剑" -> R.drawable.weapon_210
        "骑士双刃" -> R.drawable.build_weapon_013
        "鬼影长枪" -> R.drawable.weapon_212
        "鬼铜蚀" -> R.drawable.weapon_214
        "魂杵" -> R.drawable.weapon_215
        "黄沙风暴" -> R.drawable.weapon_216
        "黎明之光" -> R.drawable.weapon_218
        "黑克勒45" -> R.drawable.weapon_222
        "黑天使之刃" -> R.drawable.weapon_224
        "黑金仲裁者" -> R.drawable.weapon_226
        else -> return null
    }
    return painterResource(id = id)
}

@Composable
actual fun buildPerkPainter(name: String): Painter? {
    val id = when (name) {
        "万伤掷弹" -> R.drawable.build_perk_001
        "万钧过载" -> R.drawable.plugin_001
        "不死狂热" -> R.drawable.build_perk_002
        "不稳定弹道" -> R.drawable.build_perk_003
        "临界射界" -> R.drawable.build_perk_004
        "主武反馈" -> R.drawable.build_perk_005
        "乘胜追击" -> R.drawable.build_perk_006
        "事件视界" -> R.drawable.build_perk_007
        "五方兽临" -> R.drawable.plugin_002
        "亲密距离" -> R.drawable.plugin_003
        "亲密间距" -> R.drawable.build_perk_008
        "伏击弹药" -> R.drawable.plugin_004
        "伤害加深" -> R.drawable.plugin_005
        "伤害回血" -> R.drawable.plugin_006
        "伤害属性" -> R.drawable.build_perk_009
        "余波扩散" -> R.drawable.build_perk_010
        "余烬积势" -> R.drawable.build_perk_011
        "余震速装" -> R.drawable.plugin_007
        "使唤回弹" -> R.drawable.build_perk_012
        "元素充能" -> R.drawable.plugin_008
        "元素叠加" -> R.drawable.plugin_009
        "元素增幅" -> R.drawable.build_perk_013
        "元素延长" -> R.drawable.build_perk_014
        "元素析出" -> R.drawable.plugin_010
        "元素狂想" -> R.drawable.build_perk_015
        "元素速装" -> R.drawable.plugin_011
        "充能属性" -> R.drawable.build_perk_016
        "充能弹丸" -> R.drawable.plugin_012
        "充能弹药" -> R.drawable.plugin_013
        "充能连线" -> R.drawable.plugin_014
        "充能链路" -> R.drawable.plugin_015
        "先知箴言" -> R.drawable.plugin_016
        "光弹回收" -> R.drawable.build_perk_017
        "光效充填" -> R.drawable.build_perk_018
        "光暗冥河" -> R.drawable.build_perk_019
        "光暗冷焰" -> R.drawable.build_perk_020
        "光暗哈士奇" -> R.drawable.build_perk_021
        "光暗死神" -> R.drawable.build_perk_022
        "光暗炎帝" -> R.drawable.build_perk_023
        "光暗龙炎" -> R.drawable.build_perk_024
        "光能充能" -> R.drawable.build_perk_025
        "光谐加速" -> R.drawable.build_perk_026
        "光辉贯穿" -> R.drawable.build_perk_027
        "光隙装填" -> R.drawable.build_perk_028
        "全息充能" -> R.drawable.build_perk_029
        "全息协作" -> R.drawable.build_perk_030
        "全息速装" -> R.drawable.build_perk_031
        "共生充能" -> R.drawable.build_perk_032
        "共鸣射击" -> R.drawable.plugin_017
        "兽瞳独睐" -> R.drawable.plugin_018
        "兽躯双衍" -> R.drawable.plugin_019
        "冥河送葬" -> R.drawable.plugin_020
        "冰火引爆" -> R.drawable.plugin_021
        "冲刺得速" -> R.drawable.build_perk_033
        "冷焰爆发" -> R.drawable.build_perk_034
        "冷焰爆破" -> R.drawable.build_perk_035
        "冷焰续航" -> R.drawable.build_perk_036
        "凝神一击" -> R.drawable.build_perk_037
        "凤胆交感" -> R.drawable.plugin_022
        "出其不意" -> R.drawable.plugin_023
        "击杀掉货" -> R.drawable.build_perk_038
        "分甲化生" -> R.drawable.plugin_024
        "切换手法" -> R.drawable.build_perk_039
        "切换易伤" -> R.drawable.build_perk_040
        "切枪速攻" -> R.drawable.plugin_025
        "制导增幅" -> R.drawable.build_perk_041
        "剑摧魂" -> R.drawable.build_perk_042
        "剧毒速装" -> R.drawable.plugin_026
        "加弹抽奖" -> R.drawable.build_perk_043
        "加速蓄能" -> R.drawable.plugin_027
        "加速装填" -> R.drawable.plugin_028
        "动能释放" -> R.drawable.build_perk_044
        "动量补给" -> R.drawable.build_perk_045
        "匿踪回能" -> R.drawable.build_perk_046
        "匿踪填弹" -> R.drawable.build_perk_047
        "匿踪增伤" -> R.drawable.build_perk_048
        "十万伏特" -> R.drawable.build_perk_049
        "协同" -> R.drawable.build_perk_050
        "协同供弹" -> R.drawable.plugin_029
        "协同轰击" -> R.drawable.build_perk_051
        "协防阵列" -> R.drawable.plugin_030
        "协频共振" -> R.drawable.plugin_031
        "单体充能" -> R.drawable.build_perk_052
        "单体回弹" -> R.drawable.build_perk_053
        "单体爆发" -> R.drawable.build_perk_054
        "印照泉涌" -> R.drawable.plugin_032
        "危机充能" -> R.drawable.plugin_033
        "危机装填" -> R.drawable.plugin_034
        "危险循环" -> R.drawable.plugin_035
        "危险膛压" -> R.drawable.plugin_036
        "厄运传导" -> R.drawable.build_perk_055
        "压制火力" -> R.drawable.plugin_037
        "双星回充" -> R.drawable.build_perk_056
        "双星回响" -> R.drawable.build_perk_057
        "反哺" -> R.drawable.plugin_038
        "反弹转化" -> R.drawable.build_perk_058
        "叠伤系统" -> R.drawable.plugin_039
        "叠层增伤" -> R.drawable.plugin_040
        "叠层强化" -> R.drawable.build_perk_059
        "叠浪效应" -> R.drawable.plugin_041
        "合圈震荡" -> R.drawable.build_perk_060
        "同属回弹" -> R.drawable.plugin_042
        "同调稳持" -> R.drawable.plugin_043
        "同调装填" -> R.drawable.plugin_044
        "同调震荡" -> R.drawable.build_perk_061
        "同频装填" -> R.drawable.plugin_045
        "后台充能" -> R.drawable.build_perk_062
        "后台回弹" -> R.drawable.build_perk_063
        "后台增幅" -> R.drawable.build_perk_064
        "后台支援" -> R.drawable.build_perk_065
        "后台续能" -> R.drawable.build_perk_066
        "后台补弹" -> R.drawable.build_perk_067
        "命中储能" -> R.drawable.plugin_046
        "命中返能" -> R.drawable.plugin_047
        "哈士奇寻敌" -> R.drawable.build_perk_068
        "哈士奇支援" -> R.drawable.build_perk_069
        "哈士奇鼓舞" -> R.drawable.build_perk_070
        "哑枪" -> R.drawable.build_perk_071
        "哨令鹊起" -> R.drawable.plugin_048
        "噬能转化" -> R.drawable.plugin_049
        "回响充能" -> R.drawable.plugin_050
        "回响续装" -> R.drawable.plugin_051
        "团队填装" -> R.drawable.plugin_052
        "地裂轨迹" -> R.drawable.build_perk_072
        "地龙惊破" -> R.drawable.plugin_053
        "坍缩奇点" -> R.drawable.plugin_054
        "填弹增伤" -> R.drawable.build_perk_073
        "壁垒续航" -> R.drawable.build_perk_074
        "备弹返流" -> R.drawable.plugin_055
        "多重回能" -> R.drawable.plugin_056
        "多重回返" -> R.drawable.build_perk_075
        "多重激返" -> R.drawable.plugin_057
        "天官破煞" -> R.drawable.plugin_058
        "奇点坍缩" -> R.drawable.build_perk_076
        "威慑环爆" -> R.drawable.plugin_059
        "子弹能量" -> R.drawable.build_perk_077
        "定时震波" -> R.drawable.build_perk_078
        "定星聚元" -> R.drawable.plugin_060
        "定频加压" -> R.drawable.plugin_061
        "寒霜之怒" -> R.drawable.build_perk_079
        "寒霜协同" -> R.drawable.build_perk_080
        "导弹供能" -> R.drawable.plugin_062
        "导弹装填" -> R.drawable.plugin_063
        "导弹轰炸" -> R.drawable.build_perk_081
        "射击属性" -> R.drawable.build_perk_082
        "小弟充电" -> R.drawable.build_perk_083
        "层叠爆发" -> R.drawable.build_perk_084
        "层积强袭" -> R.drawable.plugin_064
        "层积涌流" -> R.drawable.plugin_065
        "层积裂变" -> R.drawable.plugin_066
        "属性回能" -> R.drawable.plugin_067
        "崩解协议" -> R.drawable.build_perk_085
        "崩解回涌" -> R.drawable.plugin_068
        "川流不息" -> R.drawable.plugin_069
        "川流不止" -> R.drawable.plugin_070
        "带携充能" -> R.drawable.build_perk_086
        "帽子戏法" -> R.drawable.plugin_071
        "年轮纹波" -> R.drawable.plugin_072
        "并发充能" -> R.drawable.plugin_073
        "幸运哈士奇" -> R.drawable.build_perk_087
        "幸运毒皇" -> R.drawable.build_perk_088
        "幸运炎帝" -> R.drawable.build_perk_089
        "幸运补偿" -> R.drawable.build_perk_090
        "幸运装填" -> R.drawable.plugin_074
        "幸运龙炎" -> R.drawable.build_perk_091
        "幻影力场" -> R.drawable.build_perk_092
        "开镜增幅" -> R.drawable.plugin_075
        "异态共鸣" -> R.drawable.plugin_076
        "引力弹匣" -> R.drawable.build_perk_093
        "弱点供能" -> R.drawable.plugin_077
        "弱点充能" -> R.drawable.plugin_078
        "弱点反馈" -> R.drawable.build_perk_094
        "弱点增幅" -> R.drawable.build_perk_095
        "弱点属性" -> R.drawable.build_perk_096
        "弱点必暴" -> R.drawable.build_perk_097
        "弱点续弹" -> R.drawable.plugin_079
        "弱肉强食" -> R.drawable.build_perk_098
        "弹匣超载" -> R.drawable.build_perk_099
        "弹夹扩容" -> R.drawable.build_perk_100
        "弹容共振" -> R.drawable.plugin_080
        "弹容爆破" -> R.drawable.plugin_081
        "弹幕回收" -> R.drawable.build_perk_101
        "弹药续杯" -> R.drawable.build_perk_102
        "弹跳风暴" -> R.drawable.plugin_082
        "弹速提升" -> R.drawable.plugin_083
        "弹道过载" -> R.drawable.build_perk_103
        "弹链供给" -> R.drawable.build_perk_104
        "弹雨协奏" -> R.drawable.plugin_084
        "强击火力" -> R.drawable.plugin_085
        "强化冰弹" -> R.drawable.build_perk_105
        "强袭" -> R.drawable.plugin_086
        "强袭子弹" -> R.drawable.plugin_087
        "归途" -> R.drawable.plugin_088
        "彼岸寄生" -> R.drawable.plugin_089
        "往日弹痕" -> R.drawable.build_perk_106
        "待机调节" -> R.drawable.build_perk_107
        "快速充能" -> R.drawable.build_perk_108
        "快速换弹" -> R.drawable.build_perk_109
        "快速装填" -> R.drawable.plugin_090
        "急速蓄能" -> R.drawable.plugin_091
        "急速装填" -> R.drawable.plugin_092
        "恒辉长存" -> R.drawable.build_perk_110
        "恶鬼眷顾" -> R.drawable.plugin_093
        "恶鬼腐朽" -> R.drawable.plugin_094
        "惯性制退" -> R.drawable.plugin_095
        "感染充能" -> R.drawable.plugin_096
        "感染加重" -> R.drawable.plugin_097
        "感染回弹" -> R.drawable.plugin_098
        "感染残留" -> R.drawable.build_perk_111
        "我只射击" -> R.drawable.build_perk_112
        "战术强击" -> R.drawable.plugin_099
        "战术装填" -> R.drawable.plugin_100
        "战术速装" -> R.drawable.build_perk_113
        "战灵余烬" -> R.drawable.build_perk_114
        "打标增伤" -> R.drawable.build_perk_115
        "扩容" -> R.drawable.build_perk_116
        "扩容核心" -> R.drawable.plugin_101
        "技能增幅" -> R.drawable.plugin_102
        "技能增涌" -> R.drawable.plugin_103
        "技能属性" -> R.drawable.build_perk_117
        "技能扩散" -> R.drawable.plugin_104
        "技能抽奖" -> R.drawable.build_perk_118
        "技能爆发" -> R.drawable.build_perk_119
        "技能超载" -> R.drawable.build_perk_120
        "技能震荡" -> R.drawable.build_perk_121
        "技能魔术" -> R.drawable.build_perk_122
        "折射" -> R.drawable.build_perk_123
        "抽奖充能" -> R.drawable.build_perk_124
        "抽奖回弹" -> R.drawable.build_perk_125
        "抽奖增伤" -> R.drawable.build_perk_126
        "持续压制" -> R.drawable.build_perk_127
        "捡货充能" -> R.drawable.build_perk_128
        "捡货回弹" -> R.drawable.build_perk_129
        "捡货增伤" -> R.drawable.build_perk_130
        "捡货炸环" -> R.drawable.build_perk_131
        "换弹冲击" -> R.drawable.build_perk_132
        "换弹引爆" -> R.drawable.build_perk_133
        "攻守自如" -> R.drawable.plugin_105
        "敌数减CD" -> R.drawable.build_perk_134
        "无衰射程" -> R.drawable.plugin_106
        "无限烟花" -> R.drawable.plugin_107
        "易伤回弹" -> R.drawable.build_perk_135
        "易伤回能" -> R.drawable.build_perk_136
        "易伤扩散" -> R.drawable.build_perk_137
        "星锤百击" -> R.drawable.plugin_108
        "暗影补给" -> R.drawable.build_perk_138
        "暗能余韵" -> R.drawable.build_perk_139
        "暗蚀打击" -> R.drawable.build_perk_140
        "暴伤属性" -> R.drawable.build_perk_141
        "暴击余波" -> R.drawable.build_perk_142
        "暴击属性" -> R.drawable.build_perk_143
        "暴击涌流" -> R.drawable.plugin_109
        "暴击飞弹" -> R.drawable.build_perk_144
        "暴力切换" -> R.drawable.build_perk_145
        "暴走永动" -> R.drawable.build_perk_146
        "杀戮连击" -> R.drawable.plugin_110
        "杀戮连锁" -> R.drawable.plugin_111
        "极寒之痕" -> R.drawable.build_perk_147
        "极寒之触" -> R.drawable.build_perk_148
        "极寒冰神插件1" -> R.drawable.build_perk_149
        "极寒冰神插件2" -> R.drawable.build_perk_150
        "极寒领域" -> R.drawable.build_perk_151
        "极限载弹" -> R.drawable.plugin_112
        "核爆层留" -> R.drawable.plugin_113
        "梯山架壑" -> R.drawable.plugin_114
        "棱镜聚焦" -> R.drawable.build_perk_152
        "概率坍缩" -> R.drawable.plugin_115
        "模式回能" -> R.drawable.plugin_116
        "模式填装" -> R.drawable.plugin_117
        "模式增幅" -> R.drawable.plugin_118
        "模式特化" -> R.drawable.build_perk_153
        "正中红心" -> R.drawable.plugin_119
        "武器强化" -> R.drawable.plugin_120
        "武器穿透" -> R.drawable.build_perk_154
        "武器续能" -> R.drawable.build_perk_155
        "武器驱动装置" -> R.drawable.build_perk_156
        "歼灭速装" -> R.drawable.plugin_121
        "殒命补给" -> R.drawable.plugin_122
        "毒属爆破" -> R.drawable.plugin_123
        "永动核心" -> R.drawable.build_perk_157
        "泡出暴击" -> R.drawable.build_perk_158
        "泡爆增伤" -> R.drawable.build_perk_159
        "泡碎回弹" -> R.drawable.build_perk_160
        "泡能续充" -> R.drawable.build_perk_161
        "泪纵横" -> R.drawable.build_perk_162
        "流体护盾" -> R.drawable.build_perk_163
        "流星雨" -> R.drawable.build_perk_164
        "涡轮增压" -> R.drawable.build_perk_165
        "渐稳连击" -> R.drawable.plugin_125
        "游击飞弹" -> R.drawable.build_perk_166
        "溃敌补给" -> R.drawable.build_perk_167
        "溃能结晶" -> R.drawable.build_perk_168
        "滑铲增伤" -> R.drawable.build_perk_169
        "滑铲射击" -> R.drawable.build_perk_170
        "满弹转充" -> R.drawable.build_perk_171
        "满盾充能" -> R.drawable.build_perk_172
        "满盾增幅" -> R.drawable.build_perk_173
        "满盾爆破" -> R.drawable.build_perk_174
        "满盾速装" -> R.drawable.build_perk_175
        "火力回转" -> R.drawable.plugin_126
        "火力聚焦" -> R.drawable.build_perk_176
        "火力阵线" -> R.drawable.build_perk_177
        "火神爆发" -> R.drawable.build_perk_178
        "灰烬元爆" -> R.drawable.build_perk_179
        "灰烬充能" -> R.drawable.build_perk_180
        "灰烬填弹" -> R.drawable.build_perk_181
        "灰烬增伤" -> R.drawable.build_perk_182
        "灵伴馈赠" -> R.drawable.build_perk_183
        "灵根贯髓" -> R.drawable.plugin_127
        "炎刃" -> R.drawable.plugin_128
        "点金秘术" -> R.drawable.plugin_129
        "烈焰冲击" -> R.drawable.plugin_130
        "烛影摇红" -> R.drawable.plugin_131
        "爆发" -> R.drawable.build_perk_184
        "爆发回能" -> R.drawable.plugin_132
        "爆发续航" -> R.drawable.plugin_133
        "爆毒蚀域" -> R.drawable.build_perk_185
        "爆炸属性" -> R.drawable.build_perk_186
        "爆炸烟花" -> R.drawable.plugin_134
        "爆炸直击" -> R.drawable.build_perk_187
        "爆破强化" -> R.drawable.build_perk_188
        "爆破校调" -> R.drawable.plugin_135
        "物法兼得" -> R.drawable.build_perk_189
        "狂想曲" -> R.drawable.build_perk_190
        "狂战" -> R.drawable.build_perk_191
        "狂暴装填" -> R.drawable.plugin_136
        "狂暴装弹" -> R.drawable.build_perk_192
        "狂暴连击" -> R.drawable.build_perk_193
        "狂热兽魂" -> R.drawable.plugin_137
        "狂热龙炎" -> R.drawable.build_perk_194
        "狂轰乱炸" -> R.drawable.build_perk_195
        "狙盾生成" -> R.drawable.build_perk_196
        "独弹强化" -> R.drawable.plugin_138
        "独爆产暴" -> R.drawable.build_perk_197
        "独爆充能" -> R.drawable.build_perk_198
        "独爆回弹" -> R.drawable.build_perk_199
        "独爆增伤" -> R.drawable.build_perk_200
        "狼狩" -> R.drawable.plugin_139
        "猎杀充能" -> R.drawable.plugin_140
        "猎杀装填" -> R.drawable.plugin_141
        "环震冲击" -> R.drawable.plugin_142
        "生克造化" -> R.drawable.plugin_143
        "电环疾驰" -> R.drawable.plugin_144
        "疾风充能" -> R.drawable.build_perk_201
        "疾风残影" -> R.drawable.build_perk_202
        "瘟疫之源" -> R.drawable.build_perk_203
        "白送重抽" -> R.drawable.build_perk_204
        "白骨电容器" -> R.drawable.plugin_145
        "百万伏特" -> R.drawable.plugin_146
        "盈能弹幕" -> R.drawable.build_perk_205
        "相位强袭" -> R.drawable.plugin_147
        "真空回涌" -> R.drawable.plugin_148
        "矢量制退" -> R.drawable.plugin_149
        "矩阵回充" -> R.drawable.build_perk_206
        "矩阵打击" -> R.drawable.build_perk_207
        "矩阵湮灭" -> R.drawable.build_perk_208
        "矩阵装填" -> R.drawable.build_perk_209
        "破障聚焦" -> R.drawable.build_perk_210
        "神经毒素" -> R.drawable.build_perk_211
        "神经脉冲" -> R.drawable.build_perk_212
        "积光成辉" -> R.drawable.build_perk_213
        "移速增伤" -> R.drawable.build_perk_214
        "空中补给" -> R.drawable.build_perk_215
        "空杀叠加" -> R.drawable.build_perk_216
        "空间补给" -> R.drawable.build_perk_217
        "穿甲引爆" -> R.drawable.build_perk_218
        "穿甲扩散" -> R.drawable.plugin_150
        "穿针引线" -> R.drawable.plugin_151
        "符动千金" -> R.drawable.plugin_152
        "符通万贯" -> R.drawable.plugin_153
        "精密追击" -> R.drawable.plugin_154
        "精密追踪" -> R.drawable.build_perk_219
        "精确导弹" -> R.drawable.plugin_155
        "精确能量" -> R.drawable.plugin_156
        "索命龙炎" -> R.drawable.plugin_157
        "紫奖掉物" -> R.drawable.build_perk_220
        "纯白之光" -> R.drawable.build_perk_221
        "终焉序列" -> R.drawable.plugin_158
        "绝境雷霆" -> R.drawable.build_perk_222
        "续装增量" -> R.drawable.build_perk_223
        "维度撕裂" -> R.drawable.build_perk_224
        "群伤回能" -> R.drawable.plugin_159
        "耀光爆破" -> R.drawable.build_perk_225
        "联动提升" -> R.drawable.plugin_160
        "聚焦回路" -> R.drawable.build_perk_226
        "聚能弹药" -> R.drawable.plugin_161
        "聚能弹道" -> R.drawable.plugin_162
        "聚能速度" -> R.drawable.plugin_163
        "肾上腺素" -> R.drawable.build_perk_227
        "能量溢流" -> R.drawable.build_perk_228
        "能量续抽" -> R.drawable.build_perk_229
        "腐蚀充能" -> R.drawable.build_perk_230
        "腐蚀强击" -> R.drawable.build_perk_231
        "腐蚀榴弹" -> R.drawable.plugin_164
        "腐蚀狂热" -> R.drawable.plugin_165
        "腐蚀补给" -> R.drawable.build_perk_232
        "腐蚀飞弹" -> R.drawable.build_perk_233
        "腾焰" -> R.drawable.plugin_166
        "自动龙炎" -> R.drawable.build_perk_234
        "自追踪炮塔" -> R.drawable.build_perk_235
        "致命导弹" -> R.drawable.plugin_167
        "致命射击" -> R.drawable.plugin_168
        "致命循环" -> R.drawable.plugin_169
        "致命爆炸" -> R.drawable.build_perk_236
        "致命节奏" -> R.drawable.plugin_170
        "致命节拍" -> R.drawable.plugin_171
        "致命骨矛" -> R.drawable.build_perk_237
        "蔓延" -> R.drawable.plugin_172
        "虚数汲取" -> R.drawable.plugin_173
        "虚空汲取" -> R.drawable.build_perk_238
        "虹吸充能" -> R.drawable.plugin_174
        "蚀化速装" -> R.drawable.plugin_175
        "蚀影充能" -> R.drawable.plugin_176
        "蚀烬装填" -> R.drawable.plugin_177
        "蚀速弹夹" -> R.drawable.build_perk_239
        "蜂鸣指令" -> R.drawable.plugin_178
        "蝎刺" -> R.drawable.plugin_179
        "衰变连锁" -> R.drawable.plugin_180
        "裁决充能" -> R.drawable.plugin_181
        "观山窥骨" -> R.drawable.plugin_182
        "解构增幅" -> R.drawable.plugin_183
        "解构装填" -> R.drawable.plugin_184
        "负压弹匣" -> R.drawable.plugin_185
        "负载调节" -> R.drawable.build_perk_240
        "贯长虹" -> R.drawable.build_perk_241
        "超导补给" -> R.drawable.plugin_186
        "超强技能" -> R.drawable.build_perk_242
        "超载弹匣" -> R.drawable.plugin_187
        "超限爆发" -> R.drawable.plugin_188
        "超频" -> R.drawable.plugin_189
        "超频蓄能" -> R.drawable.plugin_190
        "超频震爆" -> R.drawable.build_perk_243
        "越射越快" -> R.drawable.build_perk_244
        "跟班增伤" -> R.drawable.build_perk_245
        "跨武充能" -> R.drawable.build_perk_246
        "跳跃回能" -> R.drawable.build_perk_247
        "跳跃爆发" -> R.drawable.build_perk_248
        "跳跃省弹" -> R.drawable.build_perk_249
        "蹭枪子弹" -> R.drawable.build_perk_250
        "蹲伏优化" -> R.drawable.plugin_191
        "蹲伏充能" -> R.drawable.plugin_192
        "蹲伏增伤" -> R.drawable.plugin_193
        "蹲伏多弹" -> R.drawable.plugin_194
        "轻武速移" -> R.drawable.plugin_195
        "载弹盈能" -> R.drawable.build_perk_251
        "迁跃回路" -> R.drawable.plugin_196
        "迅积蓄能" -> R.drawable.build_perk_252
        "过载膛压" -> R.drawable.plugin_197
        "近战冲击" -> R.drawable.build_perk_253
        "近战回弹" -> R.drawable.build_perk_254
        "近战强化" -> R.drawable.build_perk_255
        "近战易伤" -> R.drawable.build_perk_256
        "近战衔接" -> R.drawable.build_perk_257
        "近距增幅" -> R.drawable.plugin_198
        "近距增效" -> R.drawable.plugin_199
        "近远联动" -> R.drawable.build_perk_258
        "远距增伤" -> R.drawable.plugin_200
        "连击充能" -> R.drawable.build_perk_259
        "连击回弹" -> R.drawable.build_perk_260
        "连发" -> R.drawable.build_perk_261
        "连射抽奖" -> R.drawable.build_perk_262
        "连抽循环" -> R.drawable.build_perk_263
        "连环震波" -> R.drawable.build_perk_264
        "连锁充能" -> R.drawable.plugin_201
        "连锁增伤" -> R.drawable.plugin_202
        "连锁电环" -> R.drawable.plugin_203
        "迟缓循环" -> R.drawable.build_perk_265
        "追猎齐射" -> R.drawable.plugin_204
        "追踪榴弹" -> R.drawable.build_perk_266
        "追身导弹" -> R.drawable.plugin_205
        "递进膛压" -> R.drawable.plugin_206
        "速伤提升" -> R.drawable.build_perk_267
        "速充增效" -> R.drawable.build_perk_268
        "速装填充" -> R.drawable.build_perk_269
        "释能火环" -> R.drawable.plugin_207
        "重峦叠势" -> R.drawable.plugin_208
        "重武护盾" -> R.drawable.build_perk_270
        "重装弹头" -> R.drawable.plugin_209
        "钝化储能" -> R.drawable.plugin_210
        "钝化充能" -> R.drawable.plugin_211
        "钝化增伤" -> R.drawable.plugin_212
        "钝化增效" -> R.drawable.plugin_213
        "钩中充能" -> R.drawable.build_perk_271
        "钩出痛打" -> R.drawable.build_perk_272
        "铲中叠伤" -> R.drawable.build_perk_273
        "铲击充能" -> R.drawable.build_perk_274
        "铲射减冷" -> R.drawable.build_perk_275
        "铲射回弹" -> R.drawable.build_perk_276
        "铲杀冲击" -> R.drawable.build_perk_277
        "铲杀得速" -> R.drawable.build_perk_278
        "链式反应" -> R.drawable.plugin_214
        "锚定攻击" -> R.drawable.plugin_215
        "长滑不衰" -> R.drawable.build_perk_279
        "长跑冠军" -> R.drawable.plugin_216
        "闪切霜环" -> R.drawable.plugin_217
        "闪回装填" -> R.drawable.plugin_218
        "闪电协议" -> R.drawable.plugin_219
        "闪电命中" -> R.drawable.build_perk_280
        "闪电轰击" -> R.drawable.plugin_220
        "闪身" -> R.drawable.plugin_221
        "防御属性" -> R.drawable.build_perk_281
        "随时待命" -> R.drawable.plugin_222
        "随机元素" -> R.drawable.plugin_223
        "隐匿出击" -> R.drawable.build_perk_282
        "雷霆增幅" -> R.drawable.build_perk_283
        "霜华" -> R.drawable.build_perk_284
        "霜滞协议" -> R.drawable.plugin_224
        "霰弹充能" -> R.drawable.plugin_225
        "霰弹回能" -> R.drawable.plugin_226
        "霰弹回补" -> R.drawable.plugin_227
        "霰弹增伤" -> R.drawable.plugin_228
        "霰弹满中" -> R.drawable.plugin_229
        "韧性齐射" -> R.drawable.build_perk_285
        "飞弹狂射" -> R.drawable.build_perk_286
        "飞毛腿" -> R.drawable.build_perk_287
        "驰射淬锋" -> R.drawable.build_perk_288
        "高频脉冲" -> R.drawable.build_perk_289
        "高频触电" -> R.drawable.plugin_230
        "鬼洞凝视" -> R.drawable.plugin_231
        "魂狩火网" -> R.drawable.build_perk_290
        "魔芋滋髓" -> R.drawable.plugin_232
        "黑洞吞噬" -> R.drawable.build_perk_291
        "黑金仲裁者插件1" -> R.drawable.build_perk_292
        "黑金仲裁者插件2" -> R.drawable.build_perk_293
        "黑金军火" -> R.drawable.build_perk_294
        "黑金遗产" -> R.drawable.build_perk_295
        "龙息奔涌" -> R.drawable.plugin_233
        "龙炎推进" -> R.drawable.plugin_234
        else -> return null
    }
    return painterResource(id = id)
}
