package com.nzd.antigravitypanel.ui.component

import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.painter.Painter
import androidx.compose.ui.res.painterResource
import com.nzd.antigravitypanel.shared.R

/**
 * 配装图片的 Android 实现。
 *
 * **这个文件是 `tools/gen_equipment_art.py` 生成的，别手改** ——
 * 物品名和资源编号的对应关系改一处就得改另一处，手改必然对不上。
 *
 * 查不到就返回 null，调用方退化成只显示名字：
 * 官方随时会出新武器，包里没有图比显示一张裂图好。
 */
@Composable
actual fun weaponPainter(name: String): Painter? {
    val id = when (name) {
        "Bully" -> R.drawable.weapon_001
        "Z型步枪" -> R.drawable.weapon_002
        "三连发步枪-抖来逆战" -> R.drawable.weapon_003
        "三连发步枪-爆米花花" -> R.drawable.weapon_004
        "三连发步枪-盒力全开" -> R.drawable.weapon_005
        "三连发步枪-逆战狂野" -> R.drawable.weapon_006
        "乘风快递-航迹" -> R.drawable.weapon_007
        "乘风快递" -> R.drawable.weapon_008
        "元宵来袭" -> R.drawable.weapon_009
        "光荣之路-祝岁" -> R.drawable.weapon_010
        "光荣之路-绝对零度" -> R.drawable.weapon_011
        "光荣之路" -> R.drawable.weapon_012
        "共晶点-野草" -> R.drawable.weapon_013
        "共晶点" -> R.drawable.weapon_014
        "再生冷却-野草" -> R.drawable.weapon_015
        "再生冷却" -> R.drawable.weapon_016
        "军用手斧" -> R.drawable.weapon_017
        "冥河之矛-凋零之煤" -> R.drawable.weapon_018
        "冥河之矛-渡魂者" -> R.drawable.weapon_019
        "冥河之矛" -> R.drawable.weapon_020
        "冰川尼泊尔" -> R.drawable.weapon_021
        "冰点双锋" -> R.drawable.weapon_022
        "冲锋枪-FDE" -> R.drawable.weapon_023
        "冲锋枪-活力四色" -> R.drawable.weapon_024
        "冲锋枪-深蓝视界" -> R.drawable.weapon_025
        "冲锋枪-烈焰狂潮" -> R.drawable.weapon_026
        "冲锋枪-逆焰快袭" -> R.drawable.weapon_027
        "冲锋枪-高能预警" -> R.drawable.weapon_028
        "利齿" -> R.drawable.weapon_029
        "制式手枪" -> R.drawable.weapon_030
        "刺锋" -> R.drawable.weapon_031
        "刺隐-野性" -> R.drawable.weapon_032
        "刺隐" -> R.drawable.weapon_033
        "哈士奇好友-全息再现" -> R.drawable.weapon_034
        "哈士奇好友" -> R.drawable.weapon_035
        "夜影之逝-降妖除魔" -> R.drawable.weapon_036
        "夜影之逝" -> R.drawable.weapon_037
        "天鹅之舞-翎蓝之翼" -> R.drawable.weapon_038
        "天鹅之舞" -> R.drawable.weapon_039
        "密林杀机" -> R.drawable.weapon_040
        "寒针" -> R.drawable.weapon_041
        "封刃" -> R.drawable.weapon_042
        "尖兵-FDE" -> R.drawable.weapon_043
        "尖兵-橄榄绿" -> R.drawable.weapon_044
        "尸龙战斧" -> R.drawable.weapon_045
        "幽冥毒王-眩目" -> R.drawable.weapon_046
        "幽冥毒王-绿潮" -> R.drawable.weapon_047
        "幽冥毒王-金牌大哥" -> R.drawable.weapon_048
        "幽冥毒王" -> R.drawable.weapon_049
        "幽冥毒皇-月陨之誓" -> R.drawable.weapon_050
        "幽冥毒皇" -> R.drawable.weapon_051
        "往日速递" -> R.drawable.weapon_052
        "心有凌兮" -> R.drawable.weapon_053
        "怒目锤" -> R.drawable.weapon_054
        "战争矩阵-暮天流霞" -> R.drawable.weapon_055
        "战争矩阵-高清重置" -> R.drawable.weapon_056
        "战争矩阵-黄金城" -> R.drawable.weapon_057
        "战争矩阵" -> R.drawable.weapon_058
        "战锋" -> R.drawable.weapon_059
        "振弦" -> R.drawable.weapon_060
        "撬棍" -> R.drawable.weapon_061
        "收割者-沙漠涂装" -> R.drawable.weapon_062
        "收割者-金炼" -> R.drawable.weapon_063
        "收割者" -> R.drawable.weapon_064
        "星尘" -> R.drawable.weapon_065
        "星海狂想" -> R.drawable.weapon_066
        "春雷震" -> R.drawable.weapon_067
        "暗夜之殇-桃瑞" -> R.drawable.weapon_068
        "暗夜之殇-炽焰" -> R.drawable.weapon_069
        "暗夜之殇-绯紫流火" -> R.drawable.weapon_070
        "暗夜之殇" -> R.drawable.weapon_071
        "曙光印记-紫电" -> R.drawable.weapon_072
        "曙光印记-薄荷" -> R.drawable.weapon_073
        "曙光印记-青霜" -> R.drawable.weapon_074
        "曙光印记" -> R.drawable.weapon_075
        "木葫芦" -> R.drawable.weapon_076
        "机枪-O力全开" -> R.drawable.weapon_077
        "机枪-冰蓝瞬击" -> R.drawable.weapon_078
        "机枪-暴雨前夜" -> R.drawable.weapon_079
        "机枪-竞技高手" -> R.drawable.weapon_080
        "机枪-耀世雷霆" -> R.drawable.weapon_081
        "机枪-陈酿精钢" -> R.drawable.weapon_082
        "杜瓦瓶-白铃" -> R.drawable.weapon_083
        "杜瓦瓶" -> R.drawable.weapon_084
        "梦魇" -> R.drawable.weapon_085
        "棒球棍" -> R.drawable.weapon_086
        "樱之殇" -> R.drawable.weapon_087
        "武装斧头" -> R.drawable.weapon_088
        "死亡之拥" -> R.drawable.weapon_089
        "死亡猎手-狩" -> R.drawable.weapon_090
        "死亡猎手-破碎网格" -> R.drawable.weapon_091
        "死亡猎手" -> R.drawable.weapon_092
        "死神猎手-幽航猎影" -> R.drawable.weapon_093
        "死神猎手-眩紫狂潮" -> R.drawable.weapon_094
        "死神猎手-紫金裁决" -> R.drawable.weapon_095
        "死神猎手" -> R.drawable.weapon_096
        "死神镰刀-幽魂" -> R.drawable.weapon_097
        "死神镰刀" -> R.drawable.weapon_098
        "沙丘之怒-红铁印记" -> R.drawable.weapon_099
        "沙丘之怒" -> R.drawable.weapon_100
        "沙暴冷锋" -> R.drawable.weapon_101
        "沙蚀重刃" -> R.drawable.weapon_102
        "浪里白条-野性" -> R.drawable.weapon_103
        "浪里白条" -> R.drawable.weapon_104
        "深渊之触" -> R.drawable.weapon_105
        "渡鸦剑" -> R.drawable.weapon_106
        "火山口" -> R.drawable.weapon_107
        "火炬" -> R.drawable.weapon_108
        "火神炎帝-探索颂歌" -> R.drawable.weapon_109
        "火神炎帝-醉梦之城" -> R.drawable.weapon_110
        "火神炎帝" -> R.drawable.weapon_111
        "炼狱双蝎- 野草" -> R.drawable.weapon_112
        "炼狱双蝎-萌点" -> R.drawable.weapon_113
        "炼狱双蝎" -> R.drawable.weapon_114
        "炼狱蝎王-光珀" -> R.drawable.weapon_115
        "炼狱蝎王-极限超频" -> R.drawable.weapon_116
        "炼狱蝎王-粉墨重华" -> R.drawable.weapon_117
        "炼狱蝎王" -> R.drawable.weapon_118
        "爆星-影" -> R.drawable.weapon_119
        "爆星" -> R.drawable.weapon_120
        "狂人电锯" -> R.drawable.weapon_121
        "狙击步枪-烈日淘金" -> R.drawable.weapon_122
        "狙击步枪-致命律动" -> R.drawable.weapon_123
        "狙击步枪-风暴少年" -> R.drawable.weapon_124
        "狙击步枪-齿轮权杖" -> R.drawable.weapon_125
        "猪猪侠捏捏乐" -> R.drawable.weapon_126
        "猪猪捏捏乐" -> R.drawable.weapon_127
        "猪猪榴弹发射器" -> R.drawable.weapon_128
        "玄凌飞刃-夏夜萤火" -> R.drawable.weapon_129
        "玄凌飞刃-幻影藏锋" -> R.drawable.weapon_130
        "玄凌飞刃" -> R.drawable.weapon_131
        "生命线-冬日耀阳" -> R.drawable.weapon_132
        "生命线-蝶与寰宇" -> R.drawable.weapon_133
        "生命线-青空橙影" -> R.drawable.weapon_134
        "生命线" -> R.drawable.weapon_135
        "甩棍" -> R.drawable.weapon_136
        "疾影逐风-朋克复兴" -> R.drawable.weapon_137
        "疾影逐风" -> R.drawable.weapon_138
        "百炼钢管" -> R.drawable.weapon_139
        "短剑" -> R.drawable.weapon_140
        "秘魇锤" -> R.drawable.weapon_141
        "稳赢之手" -> R.drawable.weapon_142
        "精绝兽神-女王权柄" -> R.drawable.weapon_143
        "精绝兽神-狂野金魂" -> R.drawable.weapon_144
        "精绝兽神-精绝冰骸" -> R.drawable.weapon_145
        "精绝兽神-黄金城" -> R.drawable.weapon_146
        "精绝兽神" -> R.drawable.weapon_147
        "纯白至上-青空橙影" -> R.drawable.weapon_148
        "纯白至上" -> R.drawable.weapon_149
        "维和者-攀登" -> R.drawable.weapon_150
        "维和者-金炼" -> R.drawable.weapon_151
        "维和者" -> R.drawable.weapon_152
        "胜利誓约-绿潮" -> R.drawable.weapon_153
        "胜利誓约" -> R.drawable.weapon_154
        "能源之影-双重冲击" -> R.drawable.weapon_155
        "能源之影-奢金" -> R.drawable.weapon_156
        "能源之影" -> R.drawable.weapon_157
        "自动步枪-枪王" -> R.drawable.weapon_158
        "自动步枪-枪神" -> R.drawable.weapon_159
        "自动步枪-静湖" -> R.drawable.weapon_160
        "自动步枪-鸿武至尊" -> R.drawable.weapon_161
        "苔色暴风-沙漠涂装" -> R.drawable.weapon_162
        "苔色暴风" -> R.drawable.weapon_163
        "葫芦" -> R.drawable.weapon_164
        "蛇神之剑" -> R.drawable.weapon_165
        "蛇神之矛" -> R.drawable.weapon_166
        "蝶翼双扇" -> R.drawable.weapon_167
        "血怨-噬魂" -> R.drawable.weapon_168
        "血怨" -> R.drawable.weapon_169
        "裁决之眼-青空橙影" -> R.drawable.weapon_170
        "裁决之眼" -> R.drawable.weapon_171
        "裂风" -> R.drawable.weapon_172
        "装置枪-双相闪" -> R.drawable.weapon_173
        "装置枪" -> R.drawable.weapon_174
        "超级复合弓-沙漠涂装" -> R.drawable.weapon_175
        "超级复合弓-航迹" -> R.drawable.weapon_176
        "超级复合弓" -> R.drawable.weapon_177
        "过载-翠柠之击" -> R.drawable.weapon_178
        "过载" -> R.drawable.weapon_179
        "迷彩先锋" -> R.drawable.weapon_180
        "逆火" -> R.drawable.weapon_181
        "钢脊" -> R.drawable.weapon_182
        "钢铁之握" -> R.drawable.weapon_183
        "钢铁游隼" -> R.drawable.weapon_184
        "钢铁轰鸣-鹰击长空" -> R.drawable.weapon_185
        "钢铁轰鸣" -> R.drawable.weapon_186
        "钢铁骑士" -> R.drawable.weapon_187
        "铁砧-FDE" -> R.drawable.weapon_188
        "铁砧-暮紫青灰" -> R.drawable.weapon_189
        "铁砧-蓝钢" -> R.drawable.weapon_190
        "铁砧" -> R.drawable.weapon_191
        "铁骨" -> R.drawable.weapon_192
        "锻星力量" -> R.drawable.weapon_193
        "防暴棍" -> R.drawable.weapon_194
        "雷霆999-暗潮" -> R.drawable.weapon_195
        "雷霆999-霓虹涂鸦" -> R.drawable.weapon_196
        "雷霆999" -> R.drawable.weapon_197
        "雷霆之影-金炼" -> R.drawable.weapon_198
        "雷霆之影-霓虹涂鸦" -> R.drawable.weapon_199
        "雷霆之影" -> R.drawable.weapon_200
        "震沙锏" -> R.drawable.weapon_201
        "霜蚀之牙" -> R.drawable.weapon_202
        "韶光樱影-航迹" -> R.drawable.weapon_203
        "韶光樱影-野草" -> R.drawable.weapon_204
        "韶光樱影" -> R.drawable.weapon_205
        "飓风之锤-沙漠涂装" -> R.drawable.weapon_206
        "飓风之锤" -> R.drawable.weapon_207
        "飓风之龙-深渊狂潮" -> R.drawable.weapon_208
        "飓风之龙" -> R.drawable.weapon_209
        "马来剑" -> R.drawable.weapon_210
        "鬼影长枪-冰砺千年" -> R.drawable.weapon_211
        "鬼影长枪" -> R.drawable.weapon_212
        "鬼铜蚀-逆火而上" -> R.drawable.weapon_213
        "鬼铜蚀" -> R.drawable.weapon_214
        "魂杵" -> R.drawable.weapon_215
        "黄沙风暴" -> R.drawable.weapon_216
        "黄金Z型步枪" -> R.drawable.weapon_217
        "黎明之光" -> R.drawable.weapon_218
        "黑克勒45-呐喊" -> R.drawable.weapon_219
        "黑克勒45-星蓝破晓" -> R.drawable.weapon_220
        "黑克勒45-金炼" -> R.drawable.weapon_221
        "黑克勒45" -> R.drawable.weapon_222
        "黑天使之刃-叶脉光流" -> R.drawable.weapon_223
        "黑天使之刃" -> R.drawable.weapon_224
        "黑金仲裁者-审判重锤" -> R.drawable.weapon_225
        "黑金仲裁者" -> R.drawable.weapon_226
        else -> return null
    }
    return painterResource(id = id)
}

@Composable
actual fun pluginPainter(name: String): Painter? {
    val id = when (name) {
        "万钧过载" -> R.drawable.plugin_001
        "五方兽临" -> R.drawable.plugin_002
        "亲密距离" -> R.drawable.plugin_003
        "伏击弹药" -> R.drawable.plugin_004
        "伤害加深" -> R.drawable.plugin_005
        "伤害回血" -> R.drawable.plugin_006
        "余震速装" -> R.drawable.plugin_007
        "元素充能" -> R.drawable.plugin_008
        "元素叠加" -> R.drawable.plugin_009
        "元素析出" -> R.drawable.plugin_010
        "元素速装" -> R.drawable.plugin_011
        "充能弹丸" -> R.drawable.plugin_012
        "充能弹药" -> R.drawable.plugin_013
        "充能连线" -> R.drawable.plugin_014
        "充能链路" -> R.drawable.plugin_015
        "先知箴言" -> R.drawable.plugin_016
        "共鸣射击" -> R.drawable.plugin_017
        "兽瞳独睐" -> R.drawable.plugin_018
        "兽躯双衍" -> R.drawable.plugin_019
        "冥河送葬" -> R.drawable.plugin_020
        "冰火引爆" -> R.drawable.plugin_021
        "凤胆交感" -> R.drawable.plugin_022
        "出其不意" -> R.drawable.plugin_023
        "分甲化生" -> R.drawable.plugin_024
        "切枪速攻" -> R.drawable.plugin_025
        "剧毒速装" -> R.drawable.plugin_026
        "加速蓄能" -> R.drawable.plugin_027
        "加速装填" -> R.drawable.plugin_028
        "协同供弹" -> R.drawable.plugin_029
        "协防阵列" -> R.drawable.plugin_030
        "协频共振" -> R.drawable.plugin_031
        "印照泉涌" -> R.drawable.plugin_032
        "危机充能" -> R.drawable.plugin_033
        "危机装填" -> R.drawable.plugin_034
        "危险循环" -> R.drawable.plugin_035
        "危险膛压" -> R.drawable.plugin_036
        "压制火力" -> R.drawable.plugin_037
        "反哺" -> R.drawable.plugin_038
        "叠伤系统" -> R.drawable.plugin_039
        "叠层增伤" -> R.drawable.plugin_040
        "叠浪效应" -> R.drawable.plugin_041
        "同属回弹" -> R.drawable.plugin_042
        "同调稳持" -> R.drawable.plugin_043
        "同调装填" -> R.drawable.plugin_044
        "同频装填" -> R.drawable.plugin_045
        "命中储能" -> R.drawable.plugin_046
        "命中返能" -> R.drawable.plugin_047
        "哨令鹊起" -> R.drawable.plugin_048
        "噬能转化" -> R.drawable.plugin_049
        "回响充能" -> R.drawable.plugin_050
        "回响续装" -> R.drawable.plugin_051
        "团队填装" -> R.drawable.plugin_052
        "地龙惊破" -> R.drawable.plugin_053
        "坍缩奇点" -> R.drawable.plugin_054
        "备弹返流" -> R.drawable.plugin_055
        "多重回能" -> R.drawable.plugin_056
        "多重激返" -> R.drawable.plugin_057
        "天官破煞" -> R.drawable.plugin_058
        "威慑环爆" -> R.drawable.plugin_059
        "定星聚元" -> R.drawable.plugin_060
        "定频加压" -> R.drawable.plugin_061
        "导弹供能" -> R.drawable.plugin_062
        "导弹装填" -> R.drawable.plugin_063
        "层积强袭" -> R.drawable.plugin_064
        "层积涌流" -> R.drawable.plugin_065
        "层积裂变" -> R.drawable.plugin_066
        "属性回能" -> R.drawable.plugin_067
        "崩解回涌" -> R.drawable.plugin_068
        "川流不息" -> R.drawable.plugin_069
        "川流不止" -> R.drawable.plugin_070
        "帽子戏法" -> R.drawable.plugin_071
        "年轮纹波" -> R.drawable.plugin_072
        "并发充能" -> R.drawable.plugin_073
        "幸运装填" -> R.drawable.plugin_074
        "开镜增幅" -> R.drawable.plugin_075
        "异态共鸣" -> R.drawable.plugin_076
        "弱点供能" -> R.drawable.plugin_077
        "弱点充能" -> R.drawable.plugin_078
        "弱点续弹" -> R.drawable.plugin_079
        "弹容共振" -> R.drawable.plugin_080
        "弹容爆破" -> R.drawable.plugin_081
        "弹跳风暴" -> R.drawable.plugin_082
        "弹速提升" -> R.drawable.plugin_083
        "弹雨协奏" -> R.drawable.plugin_084
        "强击火力" -> R.drawable.plugin_085
        "强袭" -> R.drawable.plugin_086
        "强袭子弹" -> R.drawable.plugin_087
        "归途" -> R.drawable.plugin_088
        "彼岸寄生" -> R.drawable.plugin_089
        "快速装填" -> R.drawable.plugin_090
        "急速蓄能" -> R.drawable.plugin_091
        "急速装填" -> R.drawable.plugin_092
        "恶鬼眷顾" -> R.drawable.plugin_093
        "恶鬼腐朽" -> R.drawable.plugin_094
        "惯性制退" -> R.drawable.plugin_095
        "感染充能" -> R.drawable.plugin_096
        "感染加重" -> R.drawable.plugin_097
        "感染回弹" -> R.drawable.plugin_098
        "战术强击" -> R.drawable.plugin_099
        "战术装填" -> R.drawable.plugin_100
        "扩容核心" -> R.drawable.plugin_101
        "技能增幅" -> R.drawable.plugin_102
        "技能增涌" -> R.drawable.plugin_103
        "技能扩散" -> R.drawable.plugin_104
        "攻守自如" -> R.drawable.plugin_105
        "无衰射程" -> R.drawable.plugin_106
        "无限烟花" -> R.drawable.plugin_107
        "星锤百击" -> R.drawable.plugin_108
        "暴击涌流" -> R.drawable.plugin_109
        "杀戮连击" -> R.drawable.plugin_110
        "杀戮连锁" -> R.drawable.plugin_111
        "极限载弹" -> R.drawable.plugin_112
        "核爆层留" -> R.drawable.plugin_113
        "梯山架壑" -> R.drawable.plugin_114
        "概率坍缩" -> R.drawable.plugin_115
        "模式回能" -> R.drawable.plugin_116
        "模式填装" -> R.drawable.plugin_117
        "模式增幅" -> R.drawable.plugin_118
        "正中红心" -> R.drawable.plugin_119
        "武器强化" -> R.drawable.plugin_120
        "歼灭速装" -> R.drawable.plugin_121
        "殒命补给" -> R.drawable.plugin_122
        "毒属爆破" -> R.drawable.plugin_123
        "渐入佳境" -> R.drawable.plugin_124
        "渐稳连击" -> R.drawable.plugin_125
        "火力回转" -> R.drawable.plugin_126
        "灵根贯髓" -> R.drawable.plugin_127
        "炎刃" -> R.drawable.plugin_128
        "点金秘术" -> R.drawable.plugin_129
        "烈焰冲击" -> R.drawable.plugin_130
        "烛影摇红" -> R.drawable.plugin_131
        "爆发回能" -> R.drawable.plugin_132
        "爆发续航" -> R.drawable.plugin_133
        "爆炸烟花" -> R.drawable.plugin_134
        "爆破校调" -> R.drawable.plugin_135
        "狂暴装填" -> R.drawable.plugin_136
        "狂热兽魂" -> R.drawable.plugin_137
        "独弹强化" -> R.drawable.plugin_138
        "狼狩" -> R.drawable.plugin_139
        "猎杀充能" -> R.drawable.plugin_140
        "猎杀装填" -> R.drawable.plugin_141
        "环震冲击" -> R.drawable.plugin_142
        "生克造化" -> R.drawable.plugin_143
        "电环疾驰" -> R.drawable.plugin_144
        "白骨电容器" -> R.drawable.plugin_145
        "百万伏特" -> R.drawable.plugin_146
        "相位强袭" -> R.drawable.plugin_147
        "真空回涌" -> R.drawable.plugin_148
        "矢量制退" -> R.drawable.plugin_149
        "穿甲扩散" -> R.drawable.plugin_150
        "穿针引线" -> R.drawable.plugin_151
        "符动千金" -> R.drawable.plugin_152
        "符通万贯" -> R.drawable.plugin_153
        "精密追击" -> R.drawable.plugin_154
        "精确导弹" -> R.drawable.plugin_155
        "精确能量" -> R.drawable.plugin_156
        "索命龙炎" -> R.drawable.plugin_157
        "终焉序列" -> R.drawable.plugin_158
        "群伤回能" -> R.drawable.plugin_159
        "联动提升" -> R.drawable.plugin_160
        "聚能弹药" -> R.drawable.plugin_161
        "聚能弹道" -> R.drawable.plugin_162
        "聚能速度" -> R.drawable.plugin_163
        "腐蚀榴弹" -> R.drawable.plugin_164
        "腐蚀狂热" -> R.drawable.plugin_165
        "腾焰" -> R.drawable.plugin_166
        "致命导弹" -> R.drawable.plugin_167
        "致命射击" -> R.drawable.plugin_168
        "致命循环" -> R.drawable.plugin_169
        "致命节奏" -> R.drawable.plugin_170
        "致命节拍" -> R.drawable.plugin_171
        "蔓延" -> R.drawable.plugin_172
        "虚数汲取" -> R.drawable.plugin_173
        "虹吸充能" -> R.drawable.plugin_174
        "蚀化速装" -> R.drawable.plugin_175
        "蚀影充能" -> R.drawable.plugin_176
        "蚀烬装填" -> R.drawable.plugin_177
        "蜂鸣指令" -> R.drawable.plugin_178
        "蝎刺" -> R.drawable.plugin_179
        "衰变连锁" -> R.drawable.plugin_180
        "裁决充能" -> R.drawable.plugin_181
        "观山窥骨" -> R.drawable.plugin_182
        "解构增幅" -> R.drawable.plugin_183
        "解构装填" -> R.drawable.plugin_184
        "负压弹匣" -> R.drawable.plugin_185
        "超导补给" -> R.drawable.plugin_186
        "超载弹匣" -> R.drawable.plugin_187
        "超限爆发" -> R.drawable.plugin_188
        "超频" -> R.drawable.plugin_189
        "超频蓄能" -> R.drawable.plugin_190
        "蹲伏优化" -> R.drawable.plugin_191
        "蹲伏充能" -> R.drawable.plugin_192
        "蹲伏增伤" -> R.drawable.plugin_193
        "蹲伏多弹" -> R.drawable.plugin_194
        "轻武速移" -> R.drawable.plugin_195
        "迁跃回路" -> R.drawable.plugin_196
        "过载膛压" -> R.drawable.plugin_197
        "近距增幅" -> R.drawable.plugin_198
        "近距增效" -> R.drawable.plugin_199
        "远距增伤" -> R.drawable.plugin_200
        "连锁充能" -> R.drawable.plugin_201
        "连锁增伤" -> R.drawable.plugin_202
        "连锁电环" -> R.drawable.plugin_203
        "追猎齐射" -> R.drawable.plugin_204
        "追身导弹" -> R.drawable.plugin_205
        "递进膛压" -> R.drawable.plugin_206
        "释能火环" -> R.drawable.plugin_207
        "重峦叠势" -> R.drawable.plugin_208
        "重装弹头" -> R.drawable.plugin_209
        "钝化储能" -> R.drawable.plugin_210
        "钝化充能" -> R.drawable.plugin_211
        "钝化增伤" -> R.drawable.plugin_212
        "钝化增效" -> R.drawable.plugin_213
        "链式反应" -> R.drawable.plugin_214
        "锚定攻击" -> R.drawable.plugin_215
        "长跑冠军" -> R.drawable.plugin_216
        "闪切霜环" -> R.drawable.plugin_217
        "闪回装填" -> R.drawable.plugin_218
        "闪电协议" -> R.drawable.plugin_219
        "闪电轰击" -> R.drawable.plugin_220
        "闪身" -> R.drawable.plugin_221
        "随时待命" -> R.drawable.plugin_222
        "随机元素" -> R.drawable.plugin_223
        "霜滞协议" -> R.drawable.plugin_224
        "霰弹充能" -> R.drawable.plugin_225
        "霰弹回能" -> R.drawable.plugin_226
        "霰弹回补" -> R.drawable.plugin_227
        "霰弹增伤" -> R.drawable.plugin_228
        "霰弹满中" -> R.drawable.plugin_229
        "高频触电" -> R.drawable.plugin_230
        "鬼洞凝视" -> R.drawable.plugin_231
        "魔芋滋髓" -> R.drawable.plugin_232
        "龙息奔涌" -> R.drawable.plugin_233
        "龙炎推进" -> R.drawable.plugin_234
        else -> return null
    }
    return painterResource(id = id)
}
